### PR TITLE
Big

### PR DESCRIPTION
**Pull request by abcdan**
A really big change.

I noticed the PR from @lukasvdberk in #1. It was a really good suggestion, but it consumes a lot of memory. Notice how "small" has 5 letters and "big" only has 3?

This makes my change reduce the memory for that message by 2 bytes. In my eyes, this is a lot of data saved if it's not needed at all in the first place.

### CODE REVIEW

**Comment by lukasvdberk** [comment]
True but "small" is a better coding practice and easier to understand from the developer perspective. So in that regard the codebase becomes better maintainable and stays readable.

**Comment by abcdan** [comment]
> True but "small" is a better coding practice and easier to understand from the developer perspective. So in that regard the codebase becomes better maintainable and stays readable.

Good point, but when you deploy an application on an application it'd be kind of a developer to make it as small as possible. By changing `small` to `big` we make it save 2 bytes which is enough to be used somewhere else. 

That's why I suggest this PR still get merged to avoid using an immense amount of extra memory. If needed, I can add a comment in the code.

**Comment by abcdan** [comment]
I've made the change and I'd suggest @sonofice merges it to make this script a better place for everyone 🚀

**Comment by lukasvdberk** [comment]
That is certainly true but is not the scope of this project. The scope of this project is "info.sh" and nothing more than that. If you truly want to fix this I kindly suggest to start your own fork of this project with as goal efficiency.

**Comment by abcdan** [comment]
I still think that this belongs in the scope of the application. A bash script is meant to do a simple task efficiently because you won't have to install another programming language on a Linux device because `bash` is built in.

By making it even smaller, we save more data.

**Comment by sonofice** [comment]
If I can save 2 bytes, which is a lot, with that change. I will definitely merge this with the original script. Thank you for you input.

**Comment by abcdan** [comment]
Thanks, means a lot! ✨

**Comment by lukasvdberk** [comment]
Ja maar wat de kanker gasten

**Comment by lukasvdberk** [comment]
Ignore what the person before me said. Great that this got merged!

**Pull request merged**
